# Kubernetes deployment for sentiment-analyzer app (placeholder)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analyzer
  template:
    metadata:
      labels:
        app: sentiment-analyzer
    spec:
      containers:
        - name: app
          image: sentiment-analyzer:latest
          ports:
            - containerPort: 8000
