---
- name: Provision EC2 for Sentiment Analyzer API
  hosts: all
  become: yes
  vars_files:
    - vars.yml

  vars:
    app_dir: /home/ubuntu/sentiment-analyzer-devops

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Clone project repository
      git:
        repo: https://github.com/cloudcr0w/sentiment-analyzer-devops.git
        dest: "{{ app_dir }}"
        version: main

    - name: Copy model files to app directory
      copy:
        src: "{{ playbook_dir }}/../model/{{ item }}"
        dest: "{{ app_dir }}/app/{{ item }}"
      loop:
        - model.pkl
        - vectorizer.pkl

    - name: Install Python requirements
      pip:
        requirements: "{{ app_dir }}/app/requirements.txt"
        executable: pip3

    - name: Ensure app directory is owned by ubuntu user
      file:
        path: "{{ app_dir }}"
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Kill previous uvicorn process if running
      shell: |
        pkill -f "uvicorn" || true
      ignore_errors: yes

    - name: Run FastAPI app in background
      shell: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 > /dev/null 2>&1 &
      args:
        chdir: "{{ app_dir }}/app"
